# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/

title: Webstack - RaoYi
keywords: 网址导航
description: RaoYi.net 网址收藏夹
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://webstack.raoyi.net" # the base hostname & protocol for your site, e.g. http://example.com

email: hi@raoyi.net

# Build settings
theme: minima
